### ISSUE TITLE
getImage route bug

### ISSUE THREAD

**Issue by eartharoid** [mue/api#44]
`/getImage` ✔️ 
`/getImage?category=Outdoors`✔️ 
`/getImage/1`✔️ 
`/getImage/` ❌ 
`/getImage/?category=Outdoors` ❌ 

Adding a `/` on the end causes it to attempt to fetch an image by its ID but the ID is empty.

![image](https://i.imgur.com/kpQg2oq.png)

It doesn't cause an error but it just loads forever. ![](https://i.imgur.com/m6kfSuM.png)

**Comment by davidcralph** [comment]
Can't believe API would do this 😔

**Comment by davidcralph** [comment]
Kind of fixed, it doesn't work with query but it doesn't error anymore
